# Generated by Django 3.0.5 on 2020-06-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_profile_shortkey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eductation',
            old_name='time',
            new_name='time_from',
        ),
        migrations.AddField(
            model_name='eductation',
            name='time_till',
            field=models.DateField(auto_now=True),
            preserve_default=False,
        ),
    ]
