# Generated by Django 3.0.5 on 2020-06-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200630_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eductation',
            name='time_from',
        ),
        migrations.RemoveField(
            model_name='eductation',
            name='time_till',
        ),
    ]
