# Generated by Django 3.0.5 on 2020-06-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20200630_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='eductation',
            name='time_from',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eductation',
            name='time_till',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
