# Generated by Django 3.0.5 on 2020-06-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20200630_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eductation',
            name='time_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='eductation',
            name='time_till',
            field=models.DateField(),
        ),
    ]
