# Generated by Django 3.0.5 on 2020-06-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20200630_2044'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eductation',
            new_name='Education',
        ),
    ]
