# Generated by Django 3.0.5 on 2020-06-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20200630_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionalexperience',
            old_name='time',
            new_name='time_from',
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='time_till',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
